"""Create normalized MySQL schema

Revision ID: 96a8506ee61d
Revises: 
Create Date: 2026-09-18 22:08:31.350976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a8506ee61d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hubs_code'), 'hubs', ['code'], unique=True)
    op.create_index(op.f('ix_hubs_id'), 'hubs', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('origin_hub_id', sa.Integer(), nullable=False),
    sa.Column('destination_hub_id', sa.Integer(), nullable=False),
    sa.Column('route_geometry_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['origin_hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination_hub_id'), 'routes', ['destination_hub_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_origin_hub_id'), 'routes', ['origin_hub_id'], unique=False)
    op.create_index(op.f('ix_routes_route_code'), 'routes', ['route_code'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('assigned_hub_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_assigned_hub_id'), 'vehicles', ['assigned_hub_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_code'), 'vehicles', ['vehicle_code'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('origin_hub_id', sa.Integer(), nullable=False),
    sa.Column('destination_hub_id', sa.Integer(), nullable=False),
    sa.Column('expected_next_hub_id', sa.Integer(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=True),
    sa.Column('expected_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['destination_hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['expected_next_hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['origin_hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipments_status_priority', 'shipments', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_shipments_assigned_vehicle_id'), 'shipments', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_shipments_destination_hub_id'), 'shipments', ['destination_hub_id'], unique=False)
    op.create_index(op.f('ix_shipments_expected_next_hub_id'), 'shipments', ['expected_next_hub_id'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_origin_hub_id'), 'shipments', ['origin_hub_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_id'), 'shipments', ['shipment_id'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_table('approved_reroutes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('pickup_hub_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_hub_id', sa.Integer(), nullable=False),
    sa.Column('cost_saved', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('co2_saved_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['dropoff_hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['pickup_hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_reroutes_assigned_vehicle_id'), 'approved_reroutes', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_approved_reroutes_dropoff_hub_id'), 'approved_reroutes', ['dropoff_hub_id'], unique=False)
    op.create_index(op.f('ix_approved_reroutes_id'), 'approved_reroutes', ['id'], unique=False)
    op.create_index(op.f('ix_approved_reroutes_pickup_hub_id'), 'approved_reroutes', ['pickup_hub_id'], unique=False)
    op.create_index(op.f('ix_approved_reroutes_shipment_id'), 'approved_reroutes', ['shipment_id'], unique=False)
    op.create_table('detection_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_history_id'), 'detection_history', ['id'], unique=False)
    op.create_index(op.f('ix_detection_history_shipment_id'), 'detection_history', ['shipment_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_id'), 'detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_detection_results_shipment_id'), 'detection_results', ['shipment_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_meters', sa.Float(), nullable=True),
    sa.Column('ble_gateway_id', sa.String(length=50), nullable=True),
    sa.Column('tracking_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_shipment_time', 'telemetry_events', ['shipment_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_events_assigned_vehicle_id'), 'telemetry_events', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_shipment_id'), 'telemetry_events', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_timestamp'), 'telemetry_events', ['timestamp'], unique=False)
    op.create_table('vehicle_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('from_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('to_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('transfer_hub_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['to_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['transfer_hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_transfers_from_vehicle_id'), 'vehicle_transfers', ['from_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transfers_id'), 'vehicle_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_transfers_shipment_id'), 'vehicle_transfers', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transfers_to_vehicle_id'), 'vehicle_transfers', ['to_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transfers_transfer_hub_id'), 'vehicle_transfers', ['transfer_hub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_transfers_transfer_hub_id'), table_name='vehicle_transfers')
    op.drop_index(op.f('ix_vehicle_transfers_to_vehicle_id'), table_name='vehicle_transfers')
    op.drop_index(op.f('ix_vehicle_transfers_shipment_id'), table_name='vehicle_transfers')
    op.drop_index(op.f('ix_vehicle_transfers_id'), table_name='vehicle_transfers')
    op.drop_index(op.f('ix_vehicle_transfers_from_vehicle_id'), table_name='vehicle_transfers')
    op.drop_table('vehicle_transfers')
    op.drop_index(op.f('ix_telemetry_events_timestamp'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_shipment_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_assigned_vehicle_id'), table_name='telemetry_events')
    op.drop_index('idx_telemetry_shipment_time', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_detection_results_shipment_id'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_id'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_detection_history_shipment_id'), table_name='detection_history')
    op.drop_index(op.f('ix_detection_history_id'), table_name='detection_history')
    op.drop_table('detection_history')
    op.drop_index(op.f('ix_approved_reroutes_shipment_id'), table_name='approved_reroutes')
    op.drop_index(op.f('ix_approved_reroutes_pickup_hub_id'), table_name='approved_reroutes')
    op.drop_index(op.f('ix_approved_reroutes_id'), table_name='approved_reroutes')
    op.drop_index(op.f('ix_approved_reroutes_dropoff_hub_id'), table_name='approved_reroutes')
    op.drop_index(op.f('ix_approved_reroutes_assigned_vehicle_id'), table_name='approved_reroutes')
    op.drop_table('approved_reroutes')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_origin_hub_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_expected_next_hub_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_destination_hub_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_vehicle_id'), table_name='shipments')
    op.drop_index('idx_shipments_status_priority', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_vehicles_vehicle_code'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_assigned_hub_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_routes_route_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_origin_hub_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_hub_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_hubs_id'), table_name='hubs')
    op.drop_index(op.f('ix_hubs_code'), table_name='hubs')
    op.drop_table('hubs')
    # ### end Alembic commands ###
